version: '3.7'

services:
  chatgpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatgpt
    ports:
      - 9000:9000
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./app:/home/user/api
    # stdin_open: true
    # tty: true
