version: '3.7'

services:
  chatgpt:
    image: ahmetkca/novnc:latest
    container_name: chatgpt
    ports:
      - 9000:9000
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./app:/home/python-user/app
    stdin_open: true
    tty: true
